# Site variables
title: Test GitHub Pages
description: A repository to test GitHub Pages

# Sass/SCSS
sass:
  style: :compressed

# GitHub Flavored Markdown (GFM) is default in Jekyll 4.0.0
kramdown:
  input: GFM
